# Generated by Django 2.0.7 on 2018-07-26 22:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listModel',
            fields=[
                ('lst_id', models.UUIDField(default=uuid.uuid4, help_text='id', primary_key=True, serialize=False)),
                ('lst_name', models.CharField(help_text='To store each person name', max_length=81)),
                ('lst_email', models.CharField(help_text='To store each person email', max_length=81)),
            ],
            options={
                'ordering': ['lst_name'],
            },
        ),
    ]
