# Generated by Django 2.0.7 on 2018-07-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmodel',
            name='lst_email',
            field=models.EmailField(help_text='To store each person email', max_length=81, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='listmodel',
            name='lst_name',
            field=models.CharField(help_text='To store each person name', max_length=81, verbose_name='Name'),
        ),
    ]
